Fix types

diff --git a/.bin/audit_types b/.bin/audit_types
--- a/.bin/audit_types
+++ b/.bin/audit_types
@@ -1,4 +1,5 @@
 #!/bin/bash
+# WARN Do not `set -e` (failure is manually tracked)
 
 # Type check everything
 # WARN vue-tsc requires @vue/runtime-dom (provided by Vue3 but needed in top level node_modules)
@@ -9,6 +10,7 @@ cd `dirname "$0"`
 cd ..
 
 
+# Track exit code since bash usually only sets to last command's
 EXIT_CODE=0
 
 
@@ -18,6 +20,7 @@ fi
 
 
 if [[ "$1" == "" || "$1" == "app" ]]; then
+    # NOTE Need to force tsc to show colors when piped
     node_modules/.bin/vue-tsc --project app/src --pretty | node_modules/.bin/ts-node .bin/audit_types_filter.ts || EXIT_CODE=1
 fi
 
