tooling: add rpm package warning

diff --git a/.bin/build_electron_package b/.bin/build_electron_package
--- a/.bin/build_electron_package
+++ b/.bin/build_electron_package
@@ -21,6 +21,10 @@ echo "$OSTYPE"
 # NOTE --universal packages combines x64 and arm64 together into one file (recommended by Apple)
 PLATFORM_ARGS='--mac dmg zip --universal'  # zip required for updates for dmg install
 if [[ "$OSTYPE" == "linux-gnu" ]]; then
+    if ! command -v rpmbuild &> /dev/null; then
+        echo "rpmbuild not found, install it first: sudo apt-get install rpm"
+        exit 1
+    fi
     PLATFORM_ARGS='--linux AppImage deb rpm'
 elif [[ "$OSTYPE" == "msys" ]]; then
     PLATFORM_ARGS='--windows appx portable'
